# AI Credit Risk Prediction

## Notebook 3 — Feature Engineering

**Data Source:** PostgreSQL  
**Purpose:** Convert transaction-level financial data into customer-level features.

### Input Tables
- application_train
- bureau
- bureau_balance
- previous_application
- POS_CASH_balance
- installments_payments
- credit_card_balance

### Output
Customer-level feature dataset for machine learning.

In [1]:
import pandas as pd

In [2]:
import os
import sys

PROJECT_ROOT = os.path.abspath("..")

if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

print(PROJECT_ROOT)

C:\Users\Asus\AI_Credit_Risk_Prediction

In [3]:
import importlib.util

print(importlib.util.find_spec("src"))
print(importlib.util.find_spec("src.feature_engineering"))
print(importlib.util.find_spec("src.feature_engineering.bureau_balance"))

ModuleSpec(name='src', loader=<_frozen_importlib_external.SourceFileLoader object at 0x00000299222ADAF0>, origin='C:\\Users\\Asus\\AI_Credit_Risk_Prediction\\src\\__init__.py', submodule_search_locations=['C:\\Users\\Asus\\AI_Credit_Risk_Prediction\\src'])
ModuleSpec(name='src.feature_engineering', loader=<_frozen_importlib_external.SourceFileLoader object at 0x00000299222ADAF0>, origin='C:\\Users\\Asus\\AI_Credit_Risk_Prediction\\src\\feature_engineering\\__init__.py', submodule_search_locations=['C:\\Users\\Asus\\AI_Credit_Risk_Prediction\\src\\feature_engineering'])
ModuleSpec(name='src.feature_engineering.bureau_balance', loader=<_frozen_importlib_external.SourceFileLoader object at 0x00000299222ADAF0>, origin='C:\\Users\\Asus\\AI_Credit_Risk_Prediction\\src\\feature_engineering\\bureau_balance.py')

In [4]:
print(os.listdir(r"C:\Users\Asus\AI_Credit_Risk_Prediction\src\feature_engineering"))

['.ipynb_checkpoints', 'bureau.py', 'bureau_balance.py', 'credit_card.py', 'installments.py', 'merge.py', 'pos_cash.py', 'previous_application.py', '__init__.py', '__pycache__']

In [5]:
import importlib.util

print(importlib.util.find_spec("src.feature_engineering.bureau_balance"))

ModuleSpec(name='src.feature_engineering.bureau_balance', loader=<_frozen_importlib_external.SourceFileLoader object at 0x00000299222ADAF0>, origin='C:\\Users\\Asus\\AI_Credit_Risk_Prediction\\src\\feature_engineering\\bureau_balance.py')

In [6]:
from src.feature_engineering.bureau_balance import (
    create_bureau_balance_features
)

In [7]:
import os
print(os.listdir(r"C:\Users\Asus\AI_Credit_Risk_Prediction\src\utils"))

['.ipynb_checkpoints', 'memory.py', 'validation.py', '__init__.py', '__pycache__']

In [8]:
from src.database.postgres import load_table

from src.feature_engineering.bureau_balance import (
    create_bureau_balance_features
)

bureau_balance = load_table("bureau_balance")

bureau_balance_features = create_bureau_balance_features(
    bureau_balance
)

print(bureau_balance_features.shape)

bureau_balance_features.head()

bureau_balance Loaded
============================================================
BUREAU BALANCE VALIDATION
============================================================
Shape : (9139000, 3)
Duplicate : 0
Missing Values
SK_ID_BUREAU      0
MONTHS_BALANCE    0
STATUS            0
dtype: int64
============================================================
bureau Loaded
============================================================
Bureau Balance Features Created
============================================================
(55983, 16)
(55983, 16)

,SK_ID_CURR,TOTAL_MONTHS,LATEST_MONTH,OLDEST_MONTH,STATUS_C_COUNT,STATUS_X_COUNT,STATUS_0_COUNT,STATUS_1_COUNT,STATUS_2_COUNT,STATUS_3_COUNT,STATUS_4_COUNT,STATUS_5_COUNT,DELINQUENT_MONTHS,SEVERE_DELINQUENT_MONTHS,MAX_DPD_LEVEL,AVG_DPD_LEVEL
0,100001.0,24.571429,0.00,-23.571429,15.714286,4.285714,4.428571,0.142857,0.0,0.0,0.0,0.0,0.142857,0.0,0.142857,0.007519
1,100013.0,66.000000,0.00,-65.000000,44.000000,0.000000,19.000000,3.000000,0.0,0.0,0.0,0.0,3.000000,0.0,1.000000,0.045455
2,100019.0,17.000000,0.00,-16.000000,0.000000,1.000000,16.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000
3,100032.0,19.000000,-16.75,-34.750000,0.000000,2.000000,17.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000
4,100033.0,7.000000,0.00,-6.000000,0.000000,6.000000,1.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000

In [9]:
bureau_balance_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55983 entries, 0 to 55982
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   SK_ID_CURR                55983 non-null  float64
 1   TOTAL_MONTHS              55983 non-null  float64
 2   LATEST_MONTH              55983 non-null  float64
 3   OLDEST_MONTH              55983 non-null  float64
 4   STATUS_C_COUNT            55983 non-null  float64
 5   STATUS_X_COUNT            55983 non-null  float64
 6   STATUS_0_COUNT            55983 non-null  float64
 7   STATUS_1_COUNT            55983 non-null  float64
 8   STATUS_2_COUNT            55983 non-null  float64
 9   STATUS_3_COUNT            55983 non-null  float64
 10  STATUS_4_COUNT            55983 non-null  float64
 11  STATUS_5_COUNT            55983 non-null  float64
 12  DELINQUENT_MONTHS         55983 non-null  float64
 13  SEVERE_DELINQUENT_MONTHS  55983 non-null  float64
 14  MAX_DPD_LEVEL             55983 non-null  float64
 15  AVG_DPD_LEVEL             55983 non-null  float64
dtypes: float64(16)
memory usage: 6.8 MB

In [10]:
bureau_balance_features.isnull().sum().sum()

np.int64(0)

In [11]:
bureau_balance_features.duplicated().sum()

np.int64(0)

In [12]:
bureau_balance_features.head()

,SK_ID_CURR,TOTAL_MONTHS,LATEST_MONTH,OLDEST_MONTH,STATUS_C_COUNT,STATUS_X_COUNT,STATUS_0_COUNT,STATUS_1_COUNT,STATUS_2_COUNT,STATUS_3_COUNT,STATUS_4_COUNT,STATUS_5_COUNT,DELINQUENT_MONTHS,SEVERE_DELINQUENT_MONTHS,MAX_DPD_LEVEL,AVG_DPD_LEVEL
0,100001.0,24.571429,0.00,-23.571429,15.714286,4.285714,4.428571,0.142857,0.0,0.0,0.0,0.0,0.142857,0.0,0.142857,0.007519
1,100013.0,66.000000,0.00,-65.000000,44.000000,0.000000,19.000000,3.000000,0.0,0.0,0.0,0.0,3.000000,0.0,1.000000,0.045455
2,100019.0,17.000000,0.00,-16.000000,0.000000,1.000000,16.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000
3,100032.0,19.000000,-16.75,-34.750000,0.000000,2.000000,17.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000
4,100033.0,7.000000,0.00,-6.000000,0.000000,6.000000,1.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000

In [13]:
from src.database.postgres import save_table

save_table(
    bureau_balance_features,
    "bureau_balance_features"
)

bureau_balance_features Saved

In [14]:
load_table("bureau_balance_features").head()

bureau_balance_features Loaded

,SK_ID_CURR,TOTAL_MONTHS,LATEST_MONTH,OLDEST_MONTH,STATUS_C_COUNT,STATUS_X_COUNT,STATUS_0_COUNT,STATUS_1_COUNT,STATUS_2_COUNT,STATUS_3_COUNT,STATUS_4_COUNT,STATUS_5_COUNT,DELINQUENT_MONTHS,SEVERE_DELINQUENT_MONTHS,MAX_DPD_LEVEL,AVG_DPD_LEVEL
0,100001.0,24.571429,0.00,-23.571429,15.714286,4.285714,4.428571,0.142857,0.0,0.0,0.0,0.0,0.142857,0.0,0.142857,0.007519
1,100013.0,66.000000,0.00,-65.000000,44.000000,0.000000,19.000000,3.000000,0.0,0.0,0.0,0.0,3.000000,0.0,1.000000,0.045455
2,100019.0,17.000000,0.00,-16.000000,0.000000,1.000000,16.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000
3,100032.0,19.000000,-16.75,-34.750000,0.000000,2.000000,17.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000
4,100033.0,7.000000,0.00,-6.000000,0.000000,6.000000,1.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000

In [15]:
import importlib
import src.feature_engineering.previous_application as pa

importlib.reload(pa)

In [16]:
from src.feature_engineering.previous_application import (
    clean_previous_application,
    engineer_previous_application_features
)

In [17]:
from src.database.postgres import load_table

previous_application = load_table("previous_application")

print(previous_application.shape)
previous_application.head()

previous_application Loaded
(5010642, 37)

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
previous_application = clean_previous_application(
    previous_application
)

previous_application = engineer_previous_application_features(
    previous_application
)

print(previous_application.shape)

previous_application.head()

Memory Reduced : 5090.24 MB → 4746.19 MB
(5010642, 45)

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL,IS_APPROVED,IS_REFUSED,IS_CANCELLED,IS_CONSUMER,IS_CASH,APPLICATION_CREDIT_RATIO,ANNUITY_CREDIT_RATIO,GOODS_CREDIT_RATIO
0,2030495,271877.0,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,-37.0,0.0,1,0,0,1,0,1.000000,0.100929,1.000000
1,2802425,108129.0,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,NaN,1.0,1,0,0,0,1,0.893815,0.037060,0.893815
2,2523466,122040.0,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,NaN,1.0,1,0,0,0,1,0.824511,0.110380,0.824511
3,2819243,176158.0,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,-177.0,1.0,1,0,0,0,1,0.955840,0.099920,0.955840
4,1784265,202054.0,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,NaN,NaN,0,1,0,0,1,0.835282,0.079010,0.835282

In [19]:
import importlib
import src.feature_engineering.previous_application as pa

importlib.reload(pa)

In [20]:
import importlib
import src.feature_engineering.previous_application as pa

importlib.reload(pa)

print("Reloaded Successfully")

Reloaded Successfully

In [21]:
from src.feature_engineering.previous_application import (
    create_previous_application_features
)

print(create_previous_application_features)

<function create_previous_application_features at 0x00000299280AD940>

In [22]:
previous_features = create_previous_application_features(
    previous_application
)

print(previous_features.shape)
previous_features.head()

============================================================
previous_application
============================================================
Shape : (5010642, 45)
Duplicate Rows : 3340428
Missing Values : 38111976
Infinity Values : 0
Required Columns : OK
============================================================
Memory Reduced : 5052.02 MB → 4827.43 MB
(338856, 21)

,SK_ID_CURR,PREV_APPLICATION_COUNT,APPROVED_COUNT,REFUSED_COUNT,CANCELLED_COUNT,CONSUMER_LOAN_COUNT,CASH_LOAN_COUNT,APPLICATION_AMOUNT_MEAN,APPLICATION_AMOUNT_MAX,CREDIT_AMOUNT_MEAN,...,GOODS_PRICE_MEAN,ANNUITY_MEAN,CNT_PAYMENT_MEAN,CNT_PAYMENT_MAX,DAYS_DECISION_MEAN,DAYS_DECISION_MAX,APPLICATION_CREDIT_RATIO_MEAN,APPLICATION_CREDIT_RATIO_MAX,ANNUITY_CREDIT_RATIO_MEAN,GOODS_CREDIT_RATIO_MEAN
0,100001.0,3,3,0,0,3,0,24835.50,24835.5,23787.00,...,24835.5,3951.000,8.0,8.0,-1740.0,-1740,1.044079,1.044079,0.166099,1.044079
1,100002.0,3,3,0,0,3,0,179055.00,179055.0,179055.00,...,179055.0,9251.775,24.0,24.0,-606.0,-606,1.000000,1.000000,0.051670,1.000000
2,100003.0,9,9,0,0,6,3,435436.50,900000.0,484191.00,...,435436.5,56553.990,10.0,12.0,-1305.0,-746,0.949329,1.011109,0.126383,0.949329
3,100004.0,3,3,0,0,3,0,24282.00,24282.0,20106.00,...,24282.0,5357.250,4.0,4.0,-815.0,-815,1.207699,1.207699,0.266450,1.207699
4,100005.0,6,3,0,3,3,3,22308.75,44617.5,20076.75,...,44617.5,4813.200,12.0,12.0,-536.0,-315,0.555587,1.111173,0.059935,0.555587

In [23]:
from src.database.postgres import save_table

save_table(
    previous_features,
    "previous_application_features"
)

previous_application_features Saved

In [24]:
from src.database.postgres import load_table

from src.feature_engineering.pos_cash import (
    create_pos_cash_features
)

pos_cash = load_table("pos_cash_balance")

pos_cash_features = create_pos_cash_features(
    pos_cash
)

print(pos_cash_features.shape)

pos_cash_features.head()

pos_cash_balance Loaded
============================================================
POS_CASH_balance
============================================================
Shape : (20002716, 8)
Duplicate Rows : 10001358
Missing Values : 104316
Infinity Values : 0
Required Columns : OK
============================================================
Memory Reduced : 2121.89 MB → 1454.23 MB
(337252, 21)

,SK_ID_CURR,POS_RECORD_COUNT,POS_UNIQUE_LOANS,POS_COMPLETED_COUNT,POS_ACTIVE_COUNT,POS_SIGNED_COUNT,POS_DEMAND_COUNT,POS_DPD_MEAN,POS_DPD_MAX,POS_DPD_DEF_MEAN,...,POS_INSTALMENT_MEAN,POS_INSTALMENT_MAX,POS_FUTURE_INSTALMENT_MEAN,POS_FUTURE_INSTALMENT_MAX,MONTHS_BALANCE_MIN,MONTHS_BALANCE_MAX,LATE_PAYMENT_COUNT,SEVERE_LATE_PAYMENT_COUNT,POS_LATE_RATIO,POS_SEVERE_LATE_RATIO
0,100001,18,2,4,14,0,0,0.777778,7,0.777778,...,4.000000,4.0,1.444444,4.0,-96,-53,2,2,0.111111,0.111111
1,100002,38,1,0,38,0,0,0.000000,0,0.000000,...,24.000000,24.0,15.000000,24.0,-19,-1,0,0,0.000000,0.000000
2,100003,56,3,4,52,0,0,0.000000,0,0.000000,...,10.107142,12.0,5.785714,12.0,-77,-18,0,0,0.000000,0.000000
3,100004,8,1,2,6,0,0,0.000000,0,0.000000,...,3.750000,4.0,2.250000,4.0,-27,-24,0,0,0.000000,0.000000
4,100005,22,1,2,18,2,0,0.000000,0,0.000000,...,11.700000,12.0,7.200000,12.0,-25,-15,0,0,0.000000,0.000000

In [25]:
from src.database.postgres import save_table

save_table(
    pos_cash_features,
    "pos_cash_features"
)

pos_cash_features Saved

In [26]:
from src.database.postgres import (
    load_table,
    save_table
)

from src.feature_engineering.installments import (
    create_installments_features
)

installments = load_table("installments_payments")

installment_features = create_installments_features(
    installments
)

print(installment_features.shape)

installment_features.head()

installments_payments Loaded
============================================================
installments_payments
============================================================
Shape : (13605401, 8)
Duplicate Rows : 0
Missing Values : 5810
Infinity Values : 0
Required Columns : OK
============================================================
Memory Reduced : 830.41 MB → 493.05 MB
(339587, 21)

,SK_ID_CURR,INSTALLMENT_RECORD_COUNT,UNIQUE_LOANS,LATE_PAYMENT_COUNT,EARLY_PAYMENT_COUNT,UNDERPAID_COUNT,OVERPAID_COUNT,PAYMENT_DELAY_MEAN,PAYMENT_DELAY_MAX,PAYMENT_DELAY_MIN,...,PAYMENT_RATIO_MAX,PAYMENT_RATIO_MIN,PAYMENT_DIFF_MEAN,PAYMENT_DIFF_MAX,AMT_PAYMENT_MEAN,AMT_PAYMENT_MAX,AMT_INSTALMENT_MEAN,AMT_INSTALMENT_MAX,LATE_PAYMENT_RATIO,UNDERPAID_RATIO
0,100001,7,2,1,4,0,0,-7.285714,11.0,-36.0,...,1.0,1.0,0.0,0.0,5885.132143,17397.900,5885.132143,17397.900,0.142857,0.0
1,100002,19,1,0,19,0,0,-20.421053,-12.0,-31.0,...,1.0,1.0,0.0,0.0,11559.247105,53093.745,11559.247105,53093.745,0.000000,0.0
2,100003,25,3,0,25,0,0,-7.160000,-1.0,-14.0,...,1.0,1.0,0.0,0.0,64754.586000,560835.360,64754.586000,560835.360,0.000000,0.0
3,100004,3,1,0,3,0,0,-7.666667,-3.0,-11.0,...,1.0,1.0,0.0,0.0,7096.155000,10573.965,7096.155000,10573.965,0.000000,0.0
4,100005,9,1,1,8,0,0,-23.555555,1.0,-37.0,...,1.0,1.0,0.0,0.0,6240.205000,17656.245,6240.205000,17656.245,0.111111,0.0

In [27]:
save_table(
    installment_features,
    "installment_features"
)

installment_features Saved

In [28]:
from src.database.postgres import (
    load_table,
    save_table
)

from src.feature_engineering.credit_card import (
    create_credit_card_features
)

credit_card = load_table("credit_card_balance")

credit_card_features = create_credit_card_features(
    credit_card
)

print(credit_card_features.shape)

credit_card_features.head()

credit_card_balance Loaded
============================================================
credit_card_balance
============================================================
Shape : (3840312, 23)
Duplicate Rows : 0
Missing Values : 5877356
Infinity Values : 0
Required Columns : OK
============================================================
Memory Reduced : 846.39 MB → 652.28 MB
(103558, 23)

,SK_ID_CURR,CREDIT_CARD_RECORDS,CREDIT_CARD_LOANS,BALANCE_MEAN,BALANCE_MAX,LIMIT_MEAN,LIMIT_MAX,DRAWING_MEAN,DRAWING_MAX,PAYMENT_MEAN,...,PAYMENT_BALANCE_RATIO_MEAN,DRAWING_LIMIT_RATIO_MEAN,DPD_MEAN,DPD_MAX,DPD_DEF_MEAN,DPD_DEF_MAX,LATE_COUNT,SEVERE_LATE_COUNT,LATE_RATIO,SEVERE_LATE_RATIO
0,100006,6,1,0.000000,0.00,270000.000000,270000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.000000,0,0.000000,0,0,0,0.000000,0.000000
1,100011,74,1,54482.111149,189000.00,164189.189189,180000,2432.432432,180000.0,4520.067568,...,0.966683,0.013514,0.000000,0,0.000000,0,0,0,0.000000,0.000000
2,100013,96,1,18159.919219,161420.22,131718.750000,157500,5953.125000,157500.0,6817.172344,...,4.371821,0.037798,0.010417,1,0.010417,1,1,1,0.010417,0.010417
3,100021,17,1,0.000000,0.00,675000.000000,675000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.000000,0,0.000000,0,0,0,0.000000,0.000000
4,100023,8,1,0.000000,0.00,135000.000000,225000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.000000,0,0.000000,0,0,0,0.000000,0.000000

In [29]:
save_table(
    credit_card_features,
    "credit_card_features"
)

credit_card_features Saved

In [30]:
import os

print(os.listdir(r"C:\Users\Asus\AI_Credit_Risk_Prediction\src\feature_engineering"))

['.ipynb_checkpoints', 'bureau.py', 'bureau_balance.py', 'credit_card.py', 'installments.py', 'merge.py', 'pos_cash.py', 'previous_application.py', '__init__.py', '__pycache__']

In [31]:
import importlib
import src.feature_engineering.merge as mf

importlib.reload(mf)

In [32]:
import importlib
import src.feature_engineering.bureau as bureau_module

importlib.reload(bureau_module)

In [34]:
from src.feature_engineering.bureau import create_bureau_features

In [35]:
from src.database.postgres import load_table

bureau = load_table("bureau")

bureau_features = create_bureau_features(bureau)

print(bureau_features.shape)

bureau Loaded
============================================================
bureau
============================================================
Shape : (1716428, 17)
Duplicate Rows : 0
Missing Values : 3939947
Infinity Values : 0
Required Columns : OK
============================================================
Memory Reduced : 472.82 MB → 408.99 MB
============================================================
Bureau Features Created
============================================================
(305811, 26)
(305811, 26)

In [36]:
from src.database.postgres import save_table

save_table(
    bureau_features,
    "bureau_features"
)

bureau_features Saved

In [38]:
from sqlalchemy import text
from src.database.postgres import get_engine

engine = get_engine()

with engine.connect() as conn:
    result = conn.execute(text("""
        SELECT tablename
        FROM pg_tables
        WHERE schemaname='public'
        ORDER BY tablename;
    """))
    for row in result:
        print(row[0])

application_train
bureau
bureau_balance
bureau_balance_features
bureau_features
credit_card_balance
credit_card_features
installment_features
installments_payments
pos_cash_balance
pos_cash_features
previous_application
previous_application_features

In [39]:
print(bureau_balance_features.columns)

Index(['SK_ID_CURR', 'TOTAL_MONTHS', 'LATEST_MONTH', 'OLDEST_MONTH',
       'STATUS_C_COUNT', 'STATUS_X_COUNT', 'STATUS_0_COUNT', 'STATUS_1_COUNT',
       'STATUS_2_COUNT', 'STATUS_3_COUNT', 'STATUS_4_COUNT', 'STATUS_5_COUNT',
       'DELINQUENT_MONTHS', 'SEVERE_DELINQUENT_MONTHS', 'MAX_DPD_LEVEL',
       'AVG_DPD_LEVEL'],
      dtype='object')

In [40]:
bureau_balance_features.head()

,SK_ID_CURR,TOTAL_MONTHS,LATEST_MONTH,OLDEST_MONTH,STATUS_C_COUNT,STATUS_X_COUNT,STATUS_0_COUNT,STATUS_1_COUNT,STATUS_2_COUNT,STATUS_3_COUNT,STATUS_4_COUNT,STATUS_5_COUNT,DELINQUENT_MONTHS,SEVERE_DELINQUENT_MONTHS,MAX_DPD_LEVEL,AVG_DPD_LEVEL
0,100001.0,24.571429,0.00,-23.571429,15.714286,4.285714,4.428571,0.142857,0.0,0.0,0.0,0.0,0.142857,0.0,0.142857,0.007519
1,100013.0,66.000000,0.00,-65.000000,44.000000,0.000000,19.000000,3.000000,0.0,0.0,0.0,0.0,3.000000,0.0,1.000000,0.045455
2,100019.0,17.000000,0.00,-16.000000,0.000000,1.000000,16.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000
3,100032.0,19.000000,-16.75,-34.750000,0.000000,2.000000,17.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000
4,100033.0,7.000000,0.00,-6.000000,0.000000,6.000000,1.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000

In [41]:
import importlib
import src.feature_engineering.bureau_balance as bb

importlib.reload(bb)

In [42]:
from src.feature_engineering.bureau_balance import (
    create_bureau_balance_features
)

from src.database.postgres import load_table, save_table

bureau_balance = load_table("bureau_balance")

bureau_balance_features = create_bureau_balance_features(
    bureau_balance
)

save_table(
    bureau_balance_features,
    "bureau_balance_features"
)

bureau_balance Loaded
============================================================
BUREAU BALANCE VALIDATION
============================================================
Shape : (9139000, 3)
Duplicate : 0
Missing Values
SK_ID_BUREAU      0
MONTHS_BALANCE    0
STATUS            0
dtype: int64
============================================================
bureau Loaded
============================================================
Bureau Balance Features Created
============================================================
(55983, 16)
bureau_balance_features Saved

In [43]:
print(bureau_balance_features.columns)

Index(['SK_ID_CURR', 'TOTAL_MONTHS', 'LATEST_MONTH', 'OLDEST_MONTH',
       'STATUS_C_COUNT', 'STATUS_X_COUNT', 'STATUS_0_COUNT', 'STATUS_1_COUNT',
       'STATUS_2_COUNT', 'STATUS_3_COUNT', 'STATUS_4_COUNT', 'STATUS_5_COUNT',
       'DELINQUENT_MONTHS', 'SEVERE_DELINQUENT_MONTHS', 'MAX_DPD_LEVEL',
       'AVG_DPD_LEVEL'],
      dtype='object')

In [44]:
from src.database.postgres import load_table

bureau_balance_features = load_table("bureau_balance_features")

print(bureau_balance_features.columns)
print(bureau_balance_features.shape)

bureau_balance_features Loaded
Index(['SK_ID_CURR', 'TOTAL_MONTHS', 'LATEST_MONTH', 'OLDEST_MONTH',
       'STATUS_C_COUNT', 'STATUS_X_COUNT', 'STATUS_0_COUNT', 'STATUS_1_COUNT',
       'STATUS_2_COUNT', 'STATUS_3_COUNT', 'STATUS_4_COUNT', 'STATUS_5_COUNT',
       'DELINQUENT_MONTHS', 'SEVERE_DELINQUENT_MONTHS', 'MAX_DPD_LEVEL',
       'AVG_DPD_LEVEL'],
      dtype='object')
(55983, 16)

In [45]:
from src.feature_engineering.merge import create_final_dataset

final_dataset = create_final_dataset()

print(final_dataset.shape)

application_train Loaded
bureau_features Loaded
bureau_balance_features Loaded
previous_application_features Loaded
pos_cash_features Loaded
installment_features Loaded
credit_card_features Loaded
Initial Shape : (307511, 122)
After Bureau : (307511, 147)
After Bureau Balance : (307511, 162)
After Previous : (307511, 182)
After POS CASH : (307511, 202)
After Installments : (307511, 222)
After Credit Card : (307511, 244)
============================================================
Final Dataset
============================================================
Shape : (307511, 244)
Duplicate Rows : 0
Missing Values : 764371
Infinity Values : 0
============================================================
Unique Customers : 307511
Duplicate Customers : 0
(307511, 244)

In [46]:
from src.database.postgres import save_table

save_table(
    final_dataset,
    "final_dataset"
)

final_dataset Saved